apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-ida
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        # The GitHub organization or user.
        owner: sofusalbertsen #e.g. eficode-academy
        # The Github repository
        repo: ida-upgrade #e.g. argocd-katas
        tokenRef: # your github token
          secretName: student-0-github-token # the name of the secret that contains your github token
          key: token # the key in the secret that contains your github token
        # Labels is used to filter the PRs that you want to target. (optional)
        labels:
        - test
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'todo-0-{{branch}}-{{number}}'
    spec:
      project: "default"
      source:
        repoURL: 'https://github.com/eficode-academy/helm-katas.git'
        targetRevision: 'main'
        path: examples/apps/http-server
        helm:
          parameters:
          - name: containerPort
            value: "3000"
          - name: image.repository
            value: releasepraqma/todo-app
          - name: image.tag
            value: latest
          - name: prefix
            value: ida
          - name: app
            value: "todo-{{head_short_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: student-0
      syncPolicy:
        automated:
          prune: true
          selfHeal: true